version: '3.7'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  backend:
    container_name: monorepo-backend
    build:
      context: backend
    ports:
      - '8000'
    depends_on:
      - mongo
  frontend:
    container_name: monorepo-frontend
    build:
      context: frontend
    ports:
      - '8080:80'
